services:

  database:
    container_name: database
    image: mcr.microsoft.com/azure-sql-edge:latest
    env_file:
      - ./backend/.docker.env
    volumes:
    - box-db:/var/opt/mssql
    restart: unless-stopped


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
        - ./frontend/.docker.env
    restart: unless-stopped


  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.docker.env
    depends_on:
      - database
    restart: unless-stopped

  nginx:
    container_name: ngix
    image: nginx:1.26.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  box-db: