BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Boxes] (
    [id] INT NOT NULL IDENTITY(1,1),
    [height] INT NOT NULL,
    [depth] INT NOT NULL,
    [length] INT NOT NULL,
    [comment] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Boxes_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Boxes_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
