BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Boxes] ALTER COLUMN [height] DECIMAL(32,16) NOT NULL;
ALTER TABLE [dbo].[Boxes] ALTER COLUMN [width] DECIMAL(32,16) NOT NULL;
ALTER TABLE [dbo].[Boxes] ALTER COLUMN [depth] DECIMAL(32,16) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
