name: Backend Vitest tests

on:
    push:
        branches:
            - main
        paths-ignore:
            - "documentation/**"
            - "frontend/**"

    pull_request:
        branches: [main]
        types: [opened, synchronize]
        paths-ignore:
            - "documentation/**"

jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies for backend
              run: cd backend && npm install

            - name: Run backend lint
              run: cd backend && npm run lint

    # to do
    # test:
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - uses: actions/checkout@v3
    #         - uses: actions/setup-node@v3
    #           with:
    #               node-version: "20"

    #         - name: Install dependencies for backend
    #           run: cd backend && npm install

    #         - name: Run backend tests
    #           run: cd backend && npm run test
